gem install rake 
gem install i18n 
gem install multi_json 
gem install activesupport 
gem install builder 
gem install activemodel 
gem install erubis 
gem install journey 
gem install rack 
gem install rack-cache 
gem install rack-test 
gem install hike 
gem install tilt 
gem install sprockets 
gem install actionpack 
gem install mime-types 
gem install polyglot 
gem install treetop 
gem install mail 
gem install actionmailer 
gem install arel 
gem install tzinfo 
gem install activerecord 
gem install activeresource 
gem install addressable 
gem install json 
gem install mini_portile 
gem install nokogiri 
gem install aws-sdk
gem install aws-sdk 
gem install xml-simple 
gem install aws-ses 
gem install bootstrap-sass 
gem install bundler 
gem install rack-ssl 
gem install rdoc 
gem install thor 
gem install railties 
gem install rails 
gem install bootstrap-tooltip-rails 
gem install sass 
gem install sassy-maps 
gem install breakpoint 
gem install ffi 
gem install childprocess 
gem install rubyzip 
gem install websocket 
gem install selenium-webdriver 
gem install xpath 
gem install capybara 
gem install chunky_png 
gem install coffee-script-source 
gem install execjs 
gem install coffee-script 
gem install coffee-rails 
gem install compass-core 
gem install compass-import-once 
gem install rb-fsevent 
gem install rb-inotify 
gem install compass 
gem install sass-rails 
gem install compass-rails 
gem install cookiejar 
gem install daemons 
gem install delayed_job 
gem install delayed_job_active_record 
gem install diff-lcs 
gem install eb_deployer 
gem install eventmachine 
gem install em-socksify 
gem install http_parser.rb 
gem install em-http-request 
gem install honeypot-captcha 
gem install jquery-rails 
gem install minitest 
gem install munkres 
gem install pg 
gem install rspec-core 
gem install rspec-expectations 
gem install rspec-mocks 
gem install rspec 
gem install rspec-rails 
gem install sqlite3 
gem install uglifier 
gem install valid_email 
gem install yaml_db 
