#   Ensure the SQLite 3 and MySQL 2 gems are in your Gemfile
#   gem 'sqlite3'
#   gem 'mysql2'

development:
  adapter: mysql2
  database: spliddit_production
  username: root
  password:

# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] || 'spliddit_production' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USERNAME'] || "Jon" %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  min_messages: ERROR